[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
    "djangorestframework-simplejwt>=5.4.0",
    "pillow>=11.1.0",
    "pyjwt>=2.10.1",
]
